/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGammaPool,
  IGammaPoolInterface,
} from "../../../contracts/interfaces/IGammaPool";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128[]",
        name: "amounts",
        type: "uint128[]",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lpTokens",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidity",
        type: "uint128",
      },
      {
        indexed: true,
        internalType: "enum IStrategyEvents.TX_TYPE",
        name: "txType",
        type: "uint8",
      },
    ],
    name: "ExternalSwap",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "collateral",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidity",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "writeDownAmt",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "fee",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "enum IStrategyEvents.TX_TYPE",
        name: "txType",
        type: "uint8",
      },
    ],
    name: "Liquidation",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "refId",
        type: "uint16",
      },
    ],
    name: "LoanCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128[]",
        name: "tokensHeld",
        type: "uint128[]",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidity",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "initLiquidity",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lpTokens",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint96",
        name: "rateIndex",
        type: "uint96",
      },
      {
        indexed: true,
        internalType: "enum IStrategyEvents.TX_TYPE",
        name: "txType",
        type: "uint8",
      },
    ],
    name: "LoanUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "lpTokenBalance",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lpTokenBorrowed",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint40",
        name: "lastBlockNumber",
        type: "uint40",
      },
      {
        indexed: false,
        internalType: "uint80",
        name: "accFeeIndex",
        type: "uint80",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lpTokenBorrowedPlusInterest",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "lpInvariant",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "borrowedInvariant",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128[]",
        name: "cfmmReserves",
        type: "uint128[]",
      },
      {
        indexed: true,
        internalType: "enum IStrategyEvents.TX_TYPE",
        name: "txType",
        type: "uint8",
      },
    ],
    name: "PoolUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "batchLiquidationStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
    ],
    name: "batchLiquidations",
    outputs: [
      {
        internalType: "uint256",
        name: "totalLoanLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "refund",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lpTokens",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "ratio",
        type: "uint256[]",
      },
    ],
    name: "borrowLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "liquidityBorrowed",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128[]",
        name: "tokensHeld",
        type: "uint128[]",
      },
    ],
    name: "calcInvariant",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cfmm",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "refId",
        type: "uint16",
      },
    ],
    name: "createLoan",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint128[]",
        name: "amounts",
        type: "uint128[]",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "ratio",
        type: "uint256[]",
      },
    ],
    name: "decreaseCollateral",
    outputs: [
      {
        internalType: "uint128[]",
        name: "tokensHeld",
        type: "uint128[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "depositNoPull",
    outputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "amountsDesired",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "amountsMin",
        type: "uint256[]",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "depositReserves",
    outputs: [
      {
        internalType: "uint256[]",
        name: "reserves",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCFMMBalances",
    outputs: [
      {
        internalType: "uint128[]",
        name: "cfmmReserves",
        type: "uint128[]",
      },
      {
        internalType: "uint256",
        name: "cfmmInvariant",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "cfmmTotalSupply",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFeeIndexUpdateParams",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "pool",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "emaUtilRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "emaMultiplier",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minUtilRate1",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minUtilRate2",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeDivisor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "origFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.FeeIndexUpdateParams",
        name: "data",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLastCFMMPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLatestCFMMBalances",
    outputs: [
      {
        internalType: "uint128[]",
        name: "cfmmReserves",
        type: "uint128[]",
      },
      {
        internalType: "uint256",
        name: "cfmmInvariant",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "cfmmTotalSupply",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLatestCFMMReserves",
    outputs: [
      {
        internalType: "uint128[]",
        name: "cfmmReserves",
        type: "uint128[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLoanCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getLoanData",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "rateIndex",
            type: "uint96",
          },
          {
            internalType: "uint128",
            name: "initLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "lastLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "collateral",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpTokens",
            type: "uint256",
          },
          {
            internalType: "uint128[]",
            name: "tokensHeld",
            type: "uint128[]",
          },
          {
            internalType: "address",
            name: "refAddr",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "refFee",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "refType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "px",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canLiquidate",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.LoanData",
        name: "_loanData",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "start",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "end",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    name: "getLoans",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "rateIndex",
            type: "uint96",
          },
          {
            internalType: "uint128",
            name: "initLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "lastLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "collateral",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpTokens",
            type: "uint256",
          },
          {
            internalType: "uint128[]",
            name: "tokensHeld",
            type: "uint128[]",
          },
          {
            internalType: "address",
            name: "refAddr",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "refFee",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "refType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "px",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canLiquidate",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.LoanData[]",
        name: "_loans",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    name: "getLoansById",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "rateIndex",
            type: "uint96",
          },
          {
            internalType: "uint128",
            name: "initLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "lastLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "collateral",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpTokens",
            type: "uint256",
          },
          {
            internalType: "uint128[]",
            name: "tokensHeld",
            type: "uint128[]",
          },
          {
            internalType: "address",
            name: "refAddr",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "refFee",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "refType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "px",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canLiquidate",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.LoanData[]",
        name: "_loans",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolBalances",
    outputs: [
      {
        internalType: "uint128[]",
        name: "tokenBalances",
        type: "uint128[]",
      },
      {
        internalType: "uint256",
        name: "lpTokenBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lpTokenBorrowed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lpTokenBorrowedPlusInterest",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "borrowedInvariant",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lpInvariant",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPoolData",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "protocolId",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "borrowStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "repayStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "rebalanceStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "singleLiquidationStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "batchLiquidationStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "factory",
            type: "address",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BORROWED",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BORROWED_PLUS_INTEREST",
            type: "uint256",
          },
          {
            internalType: "uint128",
            name: "BORROWED_INVARIANT",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "LP_INVARIANT",
            type: "uint128",
          },
          {
            internalType: "address",
            name: "cfmm",
            type: "address",
          },
          {
            internalType: "uint80",
            name: "accFeeIndex",
            type: "uint80",
          },
          {
            internalType: "uint8",
            name: "extSwapFee",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "origFee",
            type: "uint16",
          },
          {
            internalType: "uint40",
            name: "LAST_BLOCK_NUMBER",
            type: "uint40",
          },
          {
            internalType: "uint64",
            name: "lastCFMMFeeIndex",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "lastCFMMInvariant",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "uint128[]",
            name: "TOKEN_BALANCE",
            type: "uint128[]",
          },
          {
            internalType: "uint128[]",
            name: "CFMM_RESERVES",
            type: "uint128[]",
          },
          {
            internalType: "uint256",
            name: "lastPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "utilizationRate",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "currBlockNumber",
            type: "uint40",
          },
          {
            internalType: "uint8",
            name: "ltvThreshold",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "liquidationFee",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "supplyRate",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "emaUtilRate",
            type: "uint40",
          },
          {
            internalType: "uint8",
            name: "emaMultiplier",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "minUtilRate1",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "minUtilRate2",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "feeDivisor",
            type: "uint16",
          },
        ],
        internalType: "struct IGammaPool.PoolData",
        name: "data",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRates",
    outputs: [
      {
        internalType: "uint256",
        name: "accFeeIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastCFMMFeeIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastBlockNumber",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "ratio",
        type: "uint256[]",
      },
    ],
    name: "increaseCollateral",
    outputs: [
      {
        internalType: "uint128[]",
        name: "tokensHeld",
        type: "uint128[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_cfmm",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "_tokens",
        type: "address[]",
      },
      {
        internalType: "uint8[]",
        name: "_decimals",
        type: "uint8[]",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "liquidate",
    outputs: [
      {
        internalType: "uint256",
        name: "loanLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "refund",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "liquidateWithLP",
    outputs: [
      {
        internalType: "uint256",
        name: "loanLiquidity",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "refund",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "loan",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "rateIndex",
            type: "uint96",
          },
          {
            internalType: "uint128",
            name: "initLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "lastLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "collateral",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpTokens",
            type: "uint256",
          },
          {
            internalType: "uint128[]",
            name: "tokensHeld",
            type: "uint128[]",
          },
          {
            internalType: "address",
            name: "refAddr",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "refFee",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "refType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "px",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canLiquidate",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.LoanData",
        name: "_loanData",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "protocolId",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rateParamsStore",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "int256[]",
        name: "deltas",
        type: "int256[]",
      },
      {
        internalType: "uint256[]",
        name: "ratio",
        type: "uint256[]",
      },
    ],
    name: "rebalanceCollateral",
    outputs: [
      {
        internalType: "uint128[]",
        name: "tokensHeld",
        type: "uint128[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rebalanceStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "collateralId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "repayLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "liquidityPaid",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "ratio",
        type: "uint256[]",
      },
    ],
    name: "repayLiquiditySetRatio",
    outputs: [
      {
        internalType: "uint256",
        name: "liquidityPaid",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "collateralId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "repayLiquidityWithLP",
    outputs: [
      {
        internalType: "uint256",
        name: "liquidityPaid",
        type: "uint256",
      },
      {
        internalType: "uint128[]",
        name: "tokensHeld",
        type: "uint128[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "repayStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "origFee",
        type: "uint16",
      },
      {
        internalType: "uint8",
        name: "extSwapFee",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "emaMultiplier",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "minUtilRate1",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "minUtilRate2",
        type: "uint8",
      },
      {
        internalType: "uint16",
        name: "feeDivisor",
        type: "uint16",
      },
      {
        internalType: "uint8",
        name: "liquidationFee",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "ltvThreshold",
        type: "uint8",
      },
    ],
    name: "setPoolParams",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "shortStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "singleLiquidationStrategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "skim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sync",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tokens",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "updatePool",
    outputs: [
      {
        internalType: "uint256",
        name: "loanLiquidityDebt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "poolLiquidityDebt",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_tokens",
        type: "address[]",
      },
      {
        internalType: "address",
        name: "_cfmm",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "validateCFMM",
    outputs: [
      {
        internalType: "address[]",
        name: "_tokensOrdered",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "validateParameters",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "viewer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdrawNoPull",
    outputs: [
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdrawReserves",
    outputs: [
      {
        internalType: "uint256[]",
        name: "reserves",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGammaPool__factory {
  static readonly abi = _abi;
  static createInterface(): IGammaPoolInterface {
    return new utils.Interface(_abi) as IGammaPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGammaPool {
    return new Contract(address, _abi, signerOrProvider) as IGammaPool;
  }
}
