/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPoolViewer,
  IPoolViewerInterface,
} from "../../../contracts/interfaces/IPoolViewer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    name: "calcDynamicOriginationFee",
    outputs: [
      {
        internalType: "uint256",
        name: "origFee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "canLiquidate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "getLatestPoolData",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "protocolId",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "borrowStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "repayStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "rebalanceStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "singleLiquidationStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "batchLiquidationStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "factory",
            type: "address",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BORROWED",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BORROWED_PLUS_INTEREST",
            type: "uint256",
          },
          {
            internalType: "uint128",
            name: "BORROWED_INVARIANT",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "LP_INVARIANT",
            type: "uint128",
          },
          {
            internalType: "address",
            name: "cfmm",
            type: "address",
          },
          {
            internalType: "uint80",
            name: "accFeeIndex",
            type: "uint80",
          },
          {
            internalType: "uint8",
            name: "extSwapFee",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "origFee",
            type: "uint16",
          },
          {
            internalType: "uint40",
            name: "LAST_BLOCK_NUMBER",
            type: "uint40",
          },
          {
            internalType: "uint64",
            name: "lastCFMMFeeIndex",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "lastCFMMInvariant",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "uint128[]",
            name: "TOKEN_BALANCE",
            type: "uint128[]",
          },
          {
            internalType: "uint128[]",
            name: "CFMM_RESERVES",
            type: "uint128[]",
          },
          {
            internalType: "uint256",
            name: "lastPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "utilizationRate",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "currBlockNumber",
            type: "uint40",
          },
          {
            internalType: "uint8",
            name: "ltvThreshold",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "liquidationFee",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "supplyRate",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "emaUtilRate",
            type: "uint40",
          },
          {
            internalType: "uint8",
            name: "emaMultiplier",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "minUtilRate1",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "minUtilRate2",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "feeDivisor",
            type: "uint16",
          },
        ],
        internalType: "struct IGammaPool.PoolData",
        name: "data",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "getLatestRates",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "utilizationRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastBlockNumber",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "currBlockNumber",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "supplyRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "emaUtilRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minUtilRate1",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minUtilRate2",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "feeDivisor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "origFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
        ],
        internalType: "struct IGammaPool.RateData",
        name: "data",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "start",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "end",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    name: "getLoans",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "rateIndex",
            type: "uint96",
          },
          {
            internalType: "uint128",
            name: "initLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "lastLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "collateral",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpTokens",
            type: "uint256",
          },
          {
            internalType: "uint128[]",
            name: "tokensHeld",
            type: "uint128[]",
          },
          {
            internalType: "address",
            name: "refAddr",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "refFee",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "refType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "px",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canLiquidate",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.LoanData[]",
        name: "_loans",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "bool",
        name: "active",
        type: "bool",
      },
    ],
    name: "getLoansById",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "rateIndex",
            type: "uint96",
          },
          {
            internalType: "uint128",
            name: "initLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "lastLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "collateral",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpTokens",
            type: "uint256",
          },
          {
            internalType: "uint128[]",
            name: "tokensHeld",
            type: "uint128[]",
          },
          {
            internalType: "address",
            name: "refAddr",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "refFee",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "refType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "px",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canLiquidate",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.LoanData[]",
        name: "_loans",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
    ],
    name: "getPoolData",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "protocolId",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "borrowStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "repayStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "rebalanceStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "singleLiquidationStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "batchLiquidationStrategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "factory",
            type: "address",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BORROWED",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BORROWED_PLUS_INTEREST",
            type: "uint256",
          },
          {
            internalType: "uint128",
            name: "BORROWED_INVARIANT",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "LP_INVARIANT",
            type: "uint128",
          },
          {
            internalType: "address",
            name: "cfmm",
            type: "address",
          },
          {
            internalType: "uint80",
            name: "accFeeIndex",
            type: "uint80",
          },
          {
            internalType: "uint8",
            name: "extSwapFee",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "origFee",
            type: "uint16",
          },
          {
            internalType: "uint40",
            name: "LAST_BLOCK_NUMBER",
            type: "uint40",
          },
          {
            internalType: "uint64",
            name: "lastCFMMFeeIndex",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "lastCFMMInvariant",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "uint128[]",
            name: "TOKEN_BALANCE",
            type: "uint128[]",
          },
          {
            internalType: "uint128[]",
            name: "CFMM_RESERVES",
            type: "uint128[]",
          },
          {
            internalType: "uint256",
            name: "lastPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "borrowRate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "utilizationRate",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "currBlockNumber",
            type: "uint40",
          },
          {
            internalType: "uint8",
            name: "ltvThreshold",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "liquidationFee",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "supplyRate",
            type: "uint256",
          },
          {
            internalType: "uint40",
            name: "emaUtilRate",
            type: "uint40",
          },
          {
            internalType: "uint8",
            name: "emaMultiplier",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "minUtilRate1",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "minUtilRate2",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "feeDivisor",
            type: "uint16",
          },
        ],
        internalType: "struct IGammaPool.PoolData",
        name: "data",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_tokens",
        type: "address[]",
      },
    ],
    name: "getTokensMetaData",
    outputs: [
      {
        internalType: "string[]",
        name: "_symbols",
        type: "string[]",
      },
      {
        internalType: "string[]",
        name: "_names",
        type: "string[]",
      },
      {
        internalType: "uint8[]",
        name: "_decimals",
        type: "uint8[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "loan",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "poolId",
            type: "address",
          },
          {
            internalType: "uint96",
            name: "rateIndex",
            type: "uint96",
          },
          {
            internalType: "uint128",
            name: "initLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "lastLiquidity",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidity",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "collateral",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lpTokens",
            type: "uint256",
          },
          {
            internalType: "uint128[]",
            name: "tokensHeld",
            type: "uint128[]",
          },
          {
            internalType: "address",
            name: "refAddr",
            type: "address",
          },
          {
            internalType: "uint16",
            name: "refFee",
            type: "uint16",
          },
          {
            internalType: "uint8",
            name: "refType",
            type: "uint8",
          },
          {
            internalType: "uint256",
            name: "px",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "canLiquidate",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "accFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMFeeIndex",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LAST_BLOCK_NUMBER",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "tokens",
            type: "address[]",
          },
          {
            internalType: "uint8[]",
            name: "decimals",
            type: "uint8[]",
          },
          {
            internalType: "string[]",
            name: "symbols",
            type: "string[]",
          },
          {
            internalType: "string[]",
            name: "names",
            type: "string[]",
          },
          {
            internalType: "address",
            name: "paramsStore",
            type: "address",
          },
          {
            internalType: "address",
            name: "shortStrategy",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "BORROWED_INVARIANT",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "LP_TOKEN_BALANCE",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMInvariant",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastCFMMTotalSupply",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ltvThreshold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidationFee",
            type: "uint256",
          },
        ],
        internalType: "struct IGammaPool.LoanData",
        name: "loanData",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPoolViewer__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolViewerInterface {
    return new utils.Interface(_abi) as IPoolViewerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolViewer {
    return new Contract(address, _abi, signerOrProvider) as IPoolViewer;
  }
}
