/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as storage from "./storage";
export type { storage };
export type { ILinearKinkedRateModel } from "./ILinearKinkedRateModel";
export type { ILogDerivativeRateModel } from "./ILogDerivativeRateModel";
export type { IRateModel } from "./IRateModel";
