/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BorrowStrategy } from "./BorrowStrategy";
export type { RepayStrategy } from "./RepayStrategy";
