name: Compile/Test/Publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@gammaswap'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
      - run: yarn run test
      - run: yarn run fuzz
      - name: Echo a message
        run: echo "Pull Request Title ${{ github.event.pull_request.title }}"
      - name: Publish Package
        if: "!(contains(github.event.pull_request.title, 'skip publish'))"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
